#  settings:
#    context_name: ## replace with your context name. MUST NOT EXCEED 20 CHARACTERS AND MUST NOT CONTAIN SPACE(S)
#       temp_upload_path: '' ## the temporary upload path. MUST BE WRITABLE
#       upload_path: '' ## the upload path
#       event_handlers:
#         director.new: { class: GaEventsSampleListener, method: sampleMethod } # sample way of adding event handlers

all:
  azul_photo_uploader:
    settings:
      upload_path: 'uploads/assets'
    contexts:
      Sample:
        sizes:
          thumbnail:
            height: 150
            width: 150
          featured:
            height: 255
            width: 340
        scale:
          height: 96
          width: 290

